// SPDX-License-Identifier: MIT
//
// Self-contained SQL dumps (MySQL + PostgreSQL), schema derived from
// DATA_REFERENCE.md §6 with the adjustments in SNA.md §6.2:
//   - DROP TABLE IF EXISTS in FK-safe order: district, city, region.
//   - MySQL: utf8mb4 / utf8mb4_unicode_ci, BIGINT UNSIGNED for district_id.
//   - PostgreSQL: BIGINT, TEXT instead of VARCHAR.
//   - Geometry is NOT stored as a spatial column type. Instead the lite
//     "with bbox" representation is kept in a JSON (MySQL) / JSONB (PostgreSQL)
//     `bbox` column holding [minLon, minLat, maxLon, maxLat]. Full polygon
//     boundaries are intentionally excluded from the SQL dumps.
//   - Inserts batched 500 rows per statement; whole dump in one transaction.

import type { City, FullRegion, LiteDistrict } from './lite.js';

const BATCH = 500;

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlNumberOrNull(value: number | null): string {
  return value === null || value === undefined ? 'NULL' : String(value);
}

function sqlJson(value: unknown): string {
  // JSON serialized then quoted as a string literal. Both MySQL JSON and
  // PostgreSQL JSONB accept a JSON text literal on insert.
  return sqlString(JSON.stringify(value));
}

/** Emit batched INSERT statements for one table. */
function insertBatches(table: string, columns: string[], rows: string[][]): string {
  const out: string[] = [];
  const colList = columns.join(', ');
  for (let i = 0; i < rows.length; i += BATCH) {
    const slice = rows.slice(i, i + BATCH);
    const values = slice.map((r) => `  (${r.join(', ')})`).join(',\n');
    out.push(`INSERT INTO ${table} (${colList}) VALUES\n${values};`);
  }
  return out.join('\n');
}

interface Dialect {
  header: (generatedAt: string) => string;
  begin: string;
  commit: string;
  schema: string;
}

const mysql: Dialect = {
  header: (generatedAt) =>
    `-- Generated by saudi-national-address v1.0.0 at ${generatedAt}. Do not edit.\nSET NAMES utf8mb4;`,
  begin: 'START TRANSACTION;',
  commit: 'COMMIT;',
  schema: `DROP TABLE IF EXISTS saudi_district;
DROP TABLE IF EXISTS saudi_city;
DROP TABLE IF EXISTS saudi_region;

CREATE TABLE saudi_region (
  region_id INT UNSIGNED NOT NULL,
  code CHAR(2) NOT NULL,
  name_ar VARCHAR(128) NOT NULL,
  name_en VARCHAR(128) NOT NULL,
  population INT UNSIGNED NULL,
  capital_city_id INT UNSIGNED NULL,
  center_lat DECIMAL(10,7) NULL,
  center_lon DECIMAL(10,7) NULL,
  bbox JSON NULL,
  PRIMARY KEY (region_id),
  UNIQUE KEY uq_saudi_region_code (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE saudi_city (
  city_id INT UNSIGNED NOT NULL,
  region_id INT UNSIGNED NOT NULL,
  name_ar VARCHAR(128) NOT NULL,
  name_en VARCHAR(128) NOT NULL,
  center_lat DECIMAL(10,7) NULL,
  center_lon DECIMAL(10,7) NULL,
  PRIMARY KEY (city_id),
  KEY idx_saudi_city_region (region_id),
  CONSTRAINT fk_saudi_city_region FOREIGN KEY (region_id) REFERENCES saudi_region (region_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE saudi_district (
  district_id BIGINT UNSIGNED NOT NULL,
  city_id INT UNSIGNED NOT NULL,
  region_id INT UNSIGNED NOT NULL,
  local_seq SMALLINT UNSIGNED NOT NULL,
  name_ar VARCHAR(128) NOT NULL,
  name_en VARCHAR(128) NOT NULL,
  bbox JSON NULL,
  PRIMARY KEY (district_id),
  KEY idx_saudi_district_region_city (region_id, city_id),
  KEY idx_saudi_district_city_seq (city_id, local_seq),
  CONSTRAINT fk_saudi_district_city FOREIGN KEY (city_id) REFERENCES saudi_city (city_id),
  CONSTRAINT fk_saudi_district_region FOREIGN KEY (region_id) REFERENCES saudi_region (region_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
};

const postgres: Dialect = {
  header: (generatedAt) =>
    `-- Generated by saudi-national-address v1.0.0 at ${generatedAt}. Do not edit.`,
  begin: 'BEGIN;',
  commit: 'COMMIT;',
  schema: `DROP TABLE IF EXISTS saudi_district;
DROP TABLE IF EXISTS saudi_city;
DROP TABLE IF EXISTS saudi_region;

CREATE TABLE saudi_region (
  region_id BIGINT NOT NULL PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  name_ar TEXT NOT NULL,
  name_en TEXT NOT NULL,
  population BIGINT NULL,
  capital_city_id BIGINT NULL,
  center_lat NUMERIC(10,7) NULL,
  center_lon NUMERIC(10,7) NULL,
  bbox JSONB NULL
);

CREATE TABLE saudi_city (
  city_id BIGINT NOT NULL PRIMARY KEY,
  region_id BIGINT NOT NULL REFERENCES saudi_region (region_id),
  name_ar TEXT NOT NULL,
  name_en TEXT NOT NULL,
  center_lat NUMERIC(10,7) NULL,
  center_lon NUMERIC(10,7) NULL
);

CREATE INDEX idx_saudi_city_region ON saudi_city (region_id);

CREATE TABLE saudi_district (
  district_id BIGINT NOT NULL PRIMARY KEY,
  city_id BIGINT NOT NULL REFERENCES saudi_city (city_id),
  region_id BIGINT NOT NULL REFERENCES saudi_region (region_id),
  local_seq SMALLINT NOT NULL,
  name_ar TEXT NOT NULL,
  name_en TEXT NOT NULL,
  bbox JSONB NULL
);

CREATE INDEX idx_saudi_district_region_city ON saudi_district (region_id, city_id);
CREATE INDEX idx_saudi_district_city_seq ON saudi_district (city_id, local_seq);`,
};

function buildInserts(regions: FullRegion[], cities: City[], districts: LiteDistrict[]): string {
  const regionRows = regions.map((r) => [
    String(r.region_id),
    sqlString(r.code),
    sqlString(r.name_ar),
    sqlString(r.name_en),
    sqlNumberOrNull(r.population),
    sqlNumberOrNull(r.capital_city_id),
    String(r.center[0]),
    String(r.center[1]),
    sqlJson(r.bbox),
  ]);
  const cityRows = cities.map((c) => [
    String(c.city_id),
    String(c.region_id),
    sqlString(c.name_ar),
    sqlString(c.name_en),
    String(c.center[0]),
    String(c.center[1]),
  ]);
  const districtRows = districts.map((d) => [
    String(d.district_id),
    String(d.city_id),
    String(d.region_id),
    String(d.local_seq),
    sqlString(d.name_ar),
    sqlString(d.name_en),
    sqlJson(d.bbox),
  ]);

  return [
    insertBatches(
      'saudi_region',
      [
        'region_id',
        'code',
        'name_ar',
        'name_en',
        'population',
        'capital_city_id',
        'center_lat',
        'center_lon',
        'bbox',
      ],
      regionRows,
    ),
    insertBatches(
      'saudi_city',
      ['city_id', 'region_id', 'name_ar', 'name_en', 'center_lat', 'center_lon'],
      cityRows,
    ),
    insertBatches(
      'saudi_district',
      ['district_id', 'city_id', 'region_id', 'local_seq', 'name_ar', 'name_en', 'bbox'],
      districtRows,
    ),
  ].join('\n\n');
}

function render(
  dialect: Dialect,
  generatedAt: string,
  regions: FullRegion[],
  cities: City[],
  districts: LiteDistrict[],
): string {
  return [
    dialect.header(generatedAt),
    '',
    dialect.begin,
    '',
    dialect.schema,
    '',
    buildInserts(regions, cities, districts),
    '',
    dialect.commit,
    '',
  ].join('\n');
}

export function mysqlSql(
  generatedAt: string,
  regions: FullRegion[],
  cities: City[],
  districts: LiteDistrict[],
): string {
  return render(mysql, generatedAt, regions, cities, districts);
}

export function postgresSql(
  generatedAt: string,
  regions: FullRegion[],
  cities: City[],
  districts: LiteDistrict[],
): string {
  return render(postgres, generatedAt, regions, cities, districts);
}
